---
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "."
    groups:
      android:
        patterns:
          - "com.android.*"
          - "com.google.android.*"
      androidx:
        patterns:
          - "androidx.*"
      kotlin:
        patterns:
          - "org.jetbrains.kotlin.*"
          - "org.jetbrains.kotlinx.*"
      others:
        patterns:
          - "*"
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directories:
      - ".github/workflows"
      - ".github/actions"
    schedule:
      interval: weekly
    groups:
      actions:
        applies-to: version-updates
        update-types:
          - major
          - minor
          - patch
