---
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "."
    schedule:
      interval: daily
    groups:
      actions:
        applies-to: version-updates
        update-types:
          - major
          - minor
          - patch
